/* The catalogue. One entry per plant we sell.

   The product page reads this at runtime (?p=<slug>); the grid in plants/index.html
   is written out as static HTML from this same list, so if you add a plant here,
   add its card there too. Photography is paired: `img` is the resting shot and
   `alt` is what the card cross-fades to on hover.                              */

export const products = [
  {
    slug: 'the-monstera-pot',
    name: 'The Monstera Pot',
    species: 'Monstera deliciosa',
    chip: 'Bright light',
    price: 96,
    light: 'bright',
    water: 'low',
    size: 'medium',
    img: 'card-monstera.jpg',
    alt: 'card-monstera-alt.jpg',
    photo: 'care.jpg',
    blurb: 'A six-leaf monstera in our speckled cream pot, grown slowly under glass in Kent so the fenestrations come in wide and even. It arrives already used to a room, not a nursery.',
    care: 'Bright, indirect · water when dry',
    height: '80 to 90cm including the pot',
    specs: [
      ['Light', 'Bright, indirect. An east window is perfect.'],
      ['Water', 'When the top inch of soil is dry, roughly every 10 days.'],
      ['Pot', 'Speckled cream stoneware with a matching saucer, included.'],
      ['Pets', 'Not pet safe. Keep it off the floor if you have a chewer.'],
      ['Difficulty', 'Forgiving. It tells you what it wants.'],
    ],
    sizes: [
      { id: 'small',  label: 'Small',  note: '60cm',  price: 96 },
      { id: 'medium', label: 'Medium', note: '90cm',  price: 128, selected: true },
      { id: 'large',  label: 'Large',  note: '120cm', price: 164 },
    ],
  },
  {
    slug: 'the-fig-bundle',
    name: 'The Fig Bundle',
    species: 'Ficus lyrata',
    chip: 'Easy care',
    price: 128,
    light: 'bright',
    water: 'weekly',
    size: 'large',
    img: 'card-fig.jpg',
    alt: 'card-fig-alt.jpg',
    photo: 'card-fig-alt.jpg',
    blurb: 'A fiddle leaf fig on a slim walnut stand, sold together because the stand is what keeps the lowest leaves off a cold floor. Broad, glossy, and taller than it looks in the photograph.',
    care: 'Bright, indirect · water weekly',
    height: '120 to 140cm including the stand',
    specs: [
      ['Light', 'Bright, indirect. It will lean towards the window; turn it monthly.'],
      ['Water', 'Weekly in summer, fortnightly once the heating goes on.'],
      ['Pot', 'Terracotta, plus the walnut stand.'],
      ['Pets', 'Not pet safe.'],
      ['Difficulty', 'Steady. Hates being moved more than it hates being forgotten.'],
    ],
    sizes: [
      { id: 'standard', label: 'Standard', note: '120cm', price: 128, selected: true },
      { id: 'tall',     label: 'Tall',     note: '150cm', price: 178 },
    ],
  },
  {
    slug: 'the-root-vessel',
    name: 'The Root Vessel',
    species: 'Monstera, bare root',
    chip: 'Low water',
    price: 46,
    light: 'bright',
    water: 'low',
    size: 'small',
    img: 'card-glass.jpg',
    alt: 'card-glass-alt.jpg',
    photo: 'card-glass-alt.jpg',
    blurb: 'A rooted monstera cutting in a hand-blown glass vessel, so the root system is the point rather than something hidden under soil. Top the water up, and that is the whole job.',
    care: 'Bright, indirect · top the water up',
    height: '35 to 45cm including the vessel',
    specs: [
      ['Light', 'Bright, indirect. Direct sun will green the water.'],
      ['Water', 'Keep the roots covered. Change it every fortnight.'],
      ['Pot', 'Hand-blown glass vessel with gravel, included.'],
      ['Pets', 'Not pet safe.'],
      ['Difficulty', 'The easiest thing we sell.'],
    ],
    sizes: [
      { id: 'single', label: 'Single', note: '1 cutting',  price: 46, selected: true },
      { id: 'pair',   label: 'Pair',   note: '2 cuttings', price: 82 },
    ],
  },
  {
    slug: 'the-shade-fig',
    name: 'The Shade Fig',
    species: 'Ficus lyrata, compact',
    chip: 'Low light',
    price: 74,
    light: 'low',
    water: 'weekly',
    size: 'medium',
    img: 'card-shade-fig.jpg',
    alt: 'card-shade-fig-alt.jpg',
    photo: 'card-shade-fig-alt.jpg',
    blurb: 'The compact fig, grown under shade cloth for a season so it holds its leaves in a darker corner than its full-size sibling would tolerate.',
    care: 'Medium light · water weekly',
    height: '70 to 85cm',
    specs: [
      ['Light', 'Medium. Two metres back from a window is fine.'],
      ['Water', 'Weekly, less in winter.'],
      ['Pot', 'Terracotta with saucer, included.'],
      ['Pets', 'Not pet safe.'],
      ['Difficulty', 'Straightforward.'],
    ],
    sizes: [{ id: 'standard', label: 'Standard', note: '80cm', price: 74, selected: true }],
  },
  {
    slug: 'the-desk-cutting',
    name: 'The Desk Cutting',
    species: 'Monstera cutting',
    chip: 'Low light',
    price: 28,
    light: 'low',
    water: 'low',
    size: 'small',
    img: 'card-desk-cutting.jpg',
    alt: 'card-desk-cutting-alt.jpg',
    photo: 'card-desk-cutting-alt.jpg',
    blurb: 'One rooted node in a small glass, sized for a desk that already has a keyboard, a lamp and no room for anything else.',
    care: 'Any light · top the water up',
    height: '25cm',
    specs: [
      ['Light', 'Anything but a dark room.'],
      ['Water', 'Keep the roots covered.'],
      ['Pot', 'Small glass vessel, included.'],
      ['Pets', 'Not pet safe.'],
      ['Difficulty', 'Hard to get wrong.'],
    ],
    sizes: [{ id: 'single', label: 'Single', note: '25cm', price: 28, selected: true }],
  },
  {
    slug: 'the-corner-monstera',
    name: 'The Corner Monstera',
    species: 'Monstera deliciosa, XL',
    chip: 'Bright light',
    price: 164,
    light: 'bright',
    water: 'low',
    size: 'large',
    img: 'card-corner-monstera.jpg',
    alt: 'card-corner-monstera-alt.jpg',
    photo: 'card-corner-monstera-alt.jpg',
    blurb: 'Four years old, staked on a moss pole, and wide enough to fill the corner a sofa leaves empty. This is the one people photograph.',
    care: 'Bright, indirect · water when dry',
    height: '140 to 160cm including the pot',
    specs: [
      ['Light', 'Bright, indirect.'],
      ['Water', 'When the top two inches are dry.'],
      ['Pot', 'Speckled cream stoneware, moss pole included.'],
      ['Pets', 'Not pet safe.'],
      ['Difficulty', 'Forgiving, but it needs the space.'],
    ],
    sizes: [{ id: 'xl', label: 'Extra large', note: '150cm', price: 164, selected: true }],
  },
  {
    slug: 'the-window-fig',
    name: 'The Window Fig',
    species: 'Ficus lyrata',
    chip: 'Bright light',
    price: 98,
    light: 'bright',
    water: 'weekly',
    size: 'large',
    img: 'card-window-fig.jpg',
    alt: 'card-window-fig-alt.jpg',
    photo: 'card-window-fig-alt.jpg',
    blurb: 'A fig raised in full light, so the leaves sit closer together up the trunk. Give it the brightest spot you own and it will keep the shape.',
    care: 'Bright light · water weekly',
    height: '110 to 130cm',
    specs: [
      ['Light', 'Bright. It will take an hour or two of direct sun.'],
      ['Water', 'Weekly.'],
      ['Pot', 'Terracotta with saucer, included.'],
      ['Pets', 'Not pet safe.'],
      ['Difficulty', 'Steady.'],
    ],
    sizes: [{ id: 'standard', label: 'Standard', note: '120cm', price: 98, selected: true }],
  },
  {
    slug: 'the-glass-trio',
    name: 'The Glass Trio',
    species: 'Monstera cuttings',
    chip: 'Low water',
    price: 64,
    light: 'low',
    water: 'low',
    size: 'small',
    img: 'card-glass-trio.jpg',
    alt: 'card-glass-trio-alt.jpg',
    photo: 'card-glass-trio-alt.jpg',
    blurb: 'Three rooted cuttings in three heights of glass, meant to be grouped on a shelf where the roots catch the light from behind.',
    care: 'Any light · top the water up',
    height: '25, 35 and 45cm',
    specs: [
      ['Light', 'Anything but a dark room.'],
      ['Water', 'Keep the roots covered.'],
      ['Pot', 'Three glass vessels, included.'],
      ['Pets', 'Not pet safe.'],
      ['Difficulty', 'Hard to get wrong.'],
    ],
    sizes: [{ id: 'trio', label: 'Trio', note: '3 vessels', price: 64, selected: true }],
  },
  {
    slug: 'the-studio-monstera',
    name: 'The Studio Monstera',
    species: 'Monstera deliciosa',
    chip: 'Easy care',
    price: 118,
    light: 'bright',
    water: 'low',
    size: 'medium',
    img: 'card-studio-monstera.jpg',
    alt: 'card-studio-monstera-alt.jpg',
    photo: 'card-studio-monstera-alt.jpg',
    blurb: 'The middle size, already showing its splits, in the pot we photograph everything in. It suits a console, a desk end, or the gap beside a chair.',
    care: 'Bright, indirect · water when dry',
    height: '100 to 115cm including the pot',
    specs: [
      ['Light', 'Bright, indirect.'],
      ['Water', 'When the top inch is dry.'],
      ['Pot', 'Speckled cream stoneware with saucer, included.'],
      ['Pets', 'Not pet safe.'],
      ['Difficulty', 'Forgiving.'],
    ],
    sizes: [{ id: 'standard', label: 'Standard', note: '110cm', price: 118, selected: true }],
  },
];

export const bySlug = (slug) => products.find((p) => p.slug === slug);
